### ISSUE TITLE
Namespace prefixes stripped out from XML element keys and attributes

### ISSUE THREAD

**Issue by tim-mwangi** [clbanning/mxj#110]
If you have an XML doc with namespaces eg. a soap document and you read it into a map and write back the map into XML, the resulting string does not match the original since all the namespace prefixes are stripped out.

Example XML(missing the XML prelude that identifies it as XML):
```
<soapenv:Envelope
    xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <soapenv:Header>
        <wsse:Security
            xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
            xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" soapenv:mustUnderstand="1">
            <wsse:UsernameToken wsu:Id="UsernameToken1234">
                <wsse:Username>username123</wsse:Username>
                <wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">Password123</wsse:Password>
            </wsse:UsernameToken>
        </wsse:Security>
    </soapenv:Header>
    <soapenv:Body>
        <ns1:serviceJobUpdateRequest
            xmlns:ns1="http://example.com/ns1">
            <ns1:version>5.27</ns1:version>
            <ns1:sourceSystemName>FOOBAR</ns1:sourceSystemName>
            <ns1:sourceSystemVersion>1.0</ns1:sourceSystemVersion>
            <ns1:updateRequest>
                <ns1:requestControlID>123456</ns1:requestControlID>
                <ns1:serviceJobID>JOB12-1</ns1:serviceJobID>
                <ns1:comment>Example Comment</ns1:comment>
                <ns1:commentType>1</ns1:commentType>
            </ns1:updateRequest>
        </ns1:serviceJobUpdateRequest>
    </soapenv:Body>
</soapenv:Envelope>
```

Unit test added to test this in xml_test.go
```
var soapExample = `
<soapenv:Envelope
    xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <soapenv:Header>
        <wsse:Security
            xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
            xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" soapenv:mustUnderstand="1">
            <wsse:UsernameToken wsu:Id="UsernameToken1234">
                <wsse:Username>username123</wsse:Username>
                <wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">Password123</wsse:Password>
            </wsse:UsernameToken>
        </wsse:Security>
    </soapenv:Header>
    <soapenv:Body>
        <ns1:serviceJobUpdateRequest
            xmlns:ns1="http://example.com/ns1">
            <ns1:version>5.27</ns1:version>
            <ns1:sourceSystemName>FOOBAR</ns1:sourceSystemName>
            <ns1:sourceSystemVersion>1.0</ns1:sourceSystemVersion>
            <ns1:updateRequest>
                <ns1:requestControlID>123456</ns1:requestControlID>
                <ns1:serviceJobID>JOB12-1</ns1:serviceJobID>
                <ns1:comment>Example Comment</ns1:comment>
                <ns1:commentType>1</ns1:commentType>
            </ns1:updateRequest>
        </ns1:serviceJobUpdateRequest>
    </soapenv:Body>
</soapenv:Envelope>
`

func TestNamespacedXMLReadAndWrite(t *testing.T) {
	x := []byte(soapExample)

	mv, merr := NewMapXml(x)
	if merr != nil {
		t.Fatal("merr:", merr.Error())
	}

	buffer := &bytes.Buffer{}

	err := mv.XmlIndentWriter(buffer, "", "    ")
	if err != nil && err != io.EOF {
		t.Fatal("err:", err.Error())
	}
	wr := buffer.String()

	if wr != soapExample {
		fmt.Printf("NamespacedXMLReadAndWrite got: %s\n\n", wr)
		fmt.Printf("NamespacedXMLReadAndWrite want: %s\n", soapExample)
		t.Fatal("Not Equal")
	}
}
```

Unit test results:
```
Running tool: /usr/local/bin/go test -timeout 30s -run ^TestNamespacedXMLReadAndWrite$ github.com/clbanning/mxj/v2

NamespacedXMLReadAndWrite got: <Envelope soapenv="http://schemas.xmlsoap.org/soap/envelope/" xsd="http://www.w3.org/2001/XMLSchema" xsi="http://www.w3.org/2001/XMLSchema-instance">
    <Body>
        <serviceJobUpdateRequest ns1="http://example.com/ns1">
            <sourceSystemName>FOOBAR</sourceSystemName>
            <sourceSystemVersion>1.0</sourceSystemVersion>
            <updateRequest>
                <comment>Example Comment</comment>
                <commentType>1</commentType>
                <requestControlID>123456</requestControlID>
                <serviceJobID>JOB12-1</serviceJobID>
            </updateRequest>
            <version>5.27</version>
        </serviceJobUpdateRequest>
    </Body>
    <Header>
        <Security mustUnderstand="1" wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
            <UsernameToken Id="UsernameToken1234">
                <Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">Password123</Password>
                <Username>username123</Username>
            </UsernameToken>
        </Security>
    </Header>
</Envelope>

NamespacedXMLReadAndWrite want: <soapenv:Envelope
    xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <soapenv:Header>
        <wsse:Security
            xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"
            xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" soapenv:mustUnderstand="1">
            <wsse:UsernameToken wsu:Id="UsernameToken1234">
                <wsse:Username>username123</wsse:Username>
                <wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">Password123</wsse:Password>
            </wsse:UsernameToken>
        </wsse:Security>
    </soapenv:Header>
    <soapenv:Body>
        <ns1:serviceJobUpdateRequest
            xmlns:ns1="http://example.com/ns1">
            <ns1:version>5.27</ns1:version>
            <ns1:sourceSystemName>FOOBAR</ns1:sourceSystemName>
            <ns1:sourceSystemVersion>1.0</ns1:sourceSystemVersion>
            <ns1:updateRequest>
                <ns1:requestControlID>123456</ns1:requestControlID>
                <ns1:serviceJobID>JOB12-1</ns1:serviceJobID>
                <ns1:comment>Example Comment</ns1:comment>
                <ns1:commentType>1</ns1:commentType>
            </ns1:updateRequest>
        </ns1:serviceJobUpdateRequest>
    </soapenv:Body>
</soapenv:Envelope>

--- FAIL: TestNamespacedXMLReadAndWrite (0.00s)
    clbanning_mxj/mxj/xml_test.go:190: Not Equal
FAIL
FAIL	github.com/clbanning/mxj/v2	0.139s
FAIL
```

Note the write result is missing the namespace prefixes.

**Comment by clbanning** [comment]
Your best chance is to work with `(MapSeq)NewMapXmlSeq()` parser and the resultant `MapSeq` value.  You'll never be guaranteed equality of the XML objects using `(Map)NewMapXml()`, since `Map` doesn't understand the sequence of the XML elements/subelements.  Also, the `MapSeq` parser preserves the namespace, as is noted in the package documentation.

**Comment by tim-mwangi** [comment]
Thank you for the quick reply. I will try that out.

**Comment by tim-mwangi** [comment]
Hey @clbanning , thanks for the suggestion to use `MapSeq`. It works without issue. Now we have a different problem where if the XML doc begins with the XML identifier header i.e `<?xml version="1.0" encoding="UTF-8"?>` . This returns a `no root` error since this is being treated as a ProcInst. eg.

```
func TestNewMapXmlSeqWithXmlHeader(t *testing.T) {
	x := []byte(`<?xml version="1.0" encoding="UTF-8"?>
<doc> 
   <books>
      <book seq="1">
         <author>William T. Gaddis</author>
			<review>Gaddis is one of the most influential but little know authors in America.</review>
         <title>The Recognitions</title>
			<!-- here's the rest of the review -->
         <review>One of the great seminal American novels of the 20th century.</review>
         <review>Without it Thomas Pynchon probably wouldn't have written Gravity's Rainbow.</review>
      </book>
      <book seq="2">
         <author>Austin Tappan Wright</author>
         <title>Islandia</title>
         <review>An example of earlier 20th century American utopian fiction.</review>
      </book>
   </books>
</doc>`)

	msv, err := NewMapXmlSeq(x)
	if err != nil && err != io.EOF {
		t.Fatal("err:", err.Error())
	}
	fmt.Println("NewMapXmlSeq, x:\n", string(x))
	fmt.Println("NewMapXmlSeq, s:\n", msv.StringIndent())

	b, err := msv.XmlIndent("", "  ")
	if err != nil {
		t.Fatal("err:", err)
	}
	fmt.Println("NewMapXmlSeq, msv.XmlIndent():\n", string(b))
}
```

This unit fails:
```
Running tool: /usr/local/bin/go test -timeout 30s -run ^TestNewMapXmlSeqWithXmlHeader$ github.com/clbanning/mxj/v2

--- FAIL: TestNewMapXmlSeqWithXmlHeader (0.00s)
    clbanning_mxj/mxj/xmlseq_test.go:83: err: no root key
FAIL
FAIL	github.com/clbanning/mxj/v2	0.230s
FAIL
```
On debugging, I realized it breaks at https://github.com/clbanning/mxj/blob/cc007f32c523caac701590a6b30200ee8d573176/xmlseq.go#L408 . No issues when using `NewMapXml` because it ignores ProcInst, Comments and Directive types.

So is this by design and should the package users handle this scenario specially? Or should we integrate the special handling into the package.

I can file a different issue if it turns out this should be addressed by the package.

**Comment by clbanning** [comment]
(MapSeq)NewXmlSeqReader will let you loop through and capture leading ProcInstructions, Directives and Comments by checking the returned MapSeq value, if you want to do something with them.

In your test function try something like:

	var msv MapSeq
	var err error
	for {
		msv, err := NewMapXmlSeqReader(bytes.Reader(x))
		if err != nil {
			if err == NoRoot {
				// Handle leading #procinstr, #directive, #comment k:v if you want; even save it for later.
				// The only useful MapSeq value is a singleton with the StartElement as its key.
				// So try again to see if there's an XML doc in the Reader.
				continue
			}
			if err == io.EOF {
				// must be no valid XML doc - handle this? 
			}
			t.Fatal("err:", err.Error())
		} else {
			break   // decoded valid XML doc - so stop decoding and process it.
		}
	}
	fmt.Println("NewMapXmlSeqReader, x:\n", string(x))
	fmt.Println("NewMapXmlSeqReader, s:\n", msv.StringIndent())

	b, err := msv.XmlIndent("", "  ")
	if err != nil {
		t.Fatal("err:", err)
	}
	fmt.Println("NewMapXmlSeqReader, msv.XmlIndent():\n", string(b))

   
   ...

**Comment by tim-mwangi** [comment]
Closing this issue since the suggestions above work beautifully.

**Comment by tim-mwangi** [comment]
Thanks @clbanning for you help and rapid response!

**Comment by sunil904** [comment]
Hey, 
**x2j.XmlToJson()** when using this, the issue is still coming, is there any way to handle this?
